kind: Service
apiVersion: v1
metadata:
  name: swagger-api
  namespace: staging
spec:
  type: NodePort
  selector:
    app: swagger-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: swagger-api
