kind: Service
apiVersion: v1
metadata:
  name: swagger-editor
  namespace: staging
spec:
  type: NodePort
  selector:
    app: swagger-editor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: swagger-editor
