kind: Service
apiVersion: v1
metadata:
  name: swagger-ui
  namespace: staging
spec:
  type: NodePort
  selector:
    app: swagger-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: swagger-ui
